### PR TITLE
Allow for Multipart POST in login

### PR DESCRIPTION
**Pull request by viggyfresh**
* See code
* Should decide on a standard and stick to it 😄 `x-application-form-encoded` is surprisingly tough in JS, Multipart is easy, JSON also easy. Since responses are coming back in JSON, my gut tells me that JSON-encoded requests would keep it nice and consistent (and easy for dumb frontend devs - I had to look up the difference between form encoded and multipart form data). It is easy to mess up a form, harder to mess up JSON
* Should have gitignored build - my bad
* Tested with head of `hestia` branch on LifeDB
* This _only_ fixes login - register/other routes remain as is so we can make a plan

### CODE REVIEW

**Comment by nlandolfi** [comment]
It seems like this will be superseded by implemented JSON payloads? Is that correct?

**Comment by viggyfresh** [comment]
Yep - now you will have to figure out how to `ParseJSONForm` 😅

**Comment by viggyfresh** [comment]
Pretty standard fare - dash-cased-branches (at Palantir they enforced feature-feature-name or bugfix-bug-name, but that seemed excessive) and an informative PR message.

Yes please feel free to close.

**Comment by nlandolfi** [comment]
For posterity, see https://github.com/elos/x/pull/2

**Pull request closed without merging**
